services:
  softwaredeveloperportfolio:
    image: softwaredeveloperportfolio
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:80
